name: Build writecnblog

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build and
      run: |
        npm i
        npm run vscode:prepublish 
    - name: Dump matrix context
      run: echo ${{ toJson(matrix) }}
    - name: npm test 
      if: matrix.os == 'ubuntu-latest'
      run: xvfb-run npm test
    - name: npm test 
      if: matrix.os == 'macOS-latest' || matrix.os == 'windows-latest'
      run: npm test
